final List<Map<String, dynamic>> employees = [
  {
    "name": "Ali Khan",
    "roomNo": "101",
    "company": "Gulf Build Co.",
    "designation": "Mason",
    "status": "Assigned",
    "contact": "+971501234567",
    "currentSite": "Dubai Marina Tower",
  },
  {
    "name": "Ahmed Raza",
    "roomNo": "102",
    "company": "Al Noor Construction",
    "designation": "Labour",
    "status": "Idle",
    "contact": "+971502345678",
    "currentSite": null,
  },
  {
    "name": "Salman Ahmed",
    "roomNo": "103",
    "company": "Emirates Builders",
    "designation": "Electrician",
    "status": "Assigned",
    "contact": "+971503456789",
    "currentSite": "Expo 2025 Site",
  },
  {
    "name": "Usman Ali",
    "roomNo": "104",
    "company": "Gulf Build Co.",
    "designation": "Plumber",
    "status": "Assigned",
    "contact": "+971504567890",
    "currentSite": "Palm Jumeirah Villas",
  },
  {
    "name": "Bilal Hussain",
    "roomNo": "105",
    "company": "Al Noor Construction",
    "designation": "Mason",
    "status": "Idle",
    "contact": "+971505678901",
    "currentSite": null,
  },
  {
    "name": "Hassan Shah",
    "roomNo": "106",
    "company": "Emirates Builders",
    "designation": "Labour",
    "status": "Assigned",
    "contact": "+971506789012",
    "currentSite": "Burj Khalifa Maintenance",
  },
  {
    "name": "Imran Yousaf",
    "roomNo": "107",
    "company": "Gulf Build Co.",
    "designation": "Electrician",
    "status": "Assigned",
    "contact": "+971507890123",
    "currentSite": "Dubai Airport Expansion",
  },
  {
    "name": "Zubair Akhtar",
    "roomNo": "108",
    "company": "Al Noor Construction",
    "designation": "Plumber",
    "status": "Idle",
    "contact": "+971508901234",
    "currentSite": null,
  },
  {
    "name": "Javed Iqbal",
    "roomNo": "109",
    "company": "Emirates Builders",
    "designation": "Mason",
    "status": "Assigned",
    "contact": "+971509012345",
    "currentSite": "Business Bay Offices",
  },
  {
    "name": "Sohail Anwar",
    "roomNo": "110",
    "company": "Gulf Build Co.",
    "designation": "Labour",
    "status": "Assigned",
    "contact": "+971510123456",
    "currentSite": "Downtown Dubai Mall",
  },
  {
    "name": "Noman Aziz",
    "roomNo": "111",
    "company": "Al Noor Construction",
    "designation": "Electrician",
    "status": "Idle",
    "contact": "+971511234567",
    "currentSite": null,
  },
  {
    "name": "Rashid Khan",
    "roomNo": "112",
    "company": "Emirates Builders",
    "designation": "Plumber",
    "status": "Assigned",
    "contact": "+971512345678",
    "currentSite": "Dubai Metro Extension",
  },
  {
    "name": "Waqas Ahmad",
    "roomNo": "113",
    "company": "Gulf Build Co.",
    "designation": "Mason",
    "status": "Assigned",
    "contact": "+971513456789",
    "currentSite": "Jumeirah Beach Residences",
  },
  {
    "name": "Asad Ullah",
    "roomNo": "114",
    "company": "Al Noor Construction",
    "designation": "Labour",
    "status": "Assigned",
    "contact": "+971514567890",
    "currentSite": "Abu Dhabi Mall Project",
  },
  {
    "name": "Tariq Mehmood",
    "roomNo": "115",
    "company": "Emirates Builders",
    "designation": "Electrician",
    "status": "Idle",
    "contact": "+971515678901",
    "currentSite": null,
  },
  {
    "name": "Sajid Ali",
    "roomNo": "116",
    "company": "Gulf Build Co.",
    "designation": "Plumber",
    "status": "Assigned",
    "contact": "+971516789012",
    "currentSite": "Dubai Creek Harbour",
  },
  {
    "name": "Farhan Saeed",
    "roomNo": "117",
    "company": "Al Noor Construction",
    "designation": "Mason",
    "status": "Assigned",
    "contact": "+971517890123",
    "currentSite": "Sharjah Tower",
  },
  {
    "name": "Kamran Malik",
    "roomNo": "118",
    "company": "Emirates Builders",
    "designation": "Labour",
    "status": "Assigned",
    "contact": "+971518901234",
    "currentSite": "Yas Island Development",
  },
  {
    "name": "Adnan Hussain",
    "roomNo": "119",
    "company": "Gulf Build Co.",
    "designation": "Electrician",
    "status": "Idle",
    "contact": "+971519012345",
    "currentSite": null,
  },
  {
    "name": "Zeeshan Akram",
    "roomNo": "120",
    "company": "Al Noor Construction",
    "designation": "Plumber",
    "status": "Assigned",
    "contact": "+971520123456",
    "currentSite": "Dubai Hills Project",
  },
];
